trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.5.0'

steps:
# Install Terraform
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.5.0'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform plan -var-file="terraform.tfvars"
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve -var-file="terraform.tfvars"
  displayName: 'Terraform Apply'
- script: |
    echo "Resource Group: $(resource_group)"
    echo "Virtual Network: $(vnet)"
    echo "Subnet: $(subnet)"
    echo "Network Security Group: $(nsg)"
    echo "Storage Account: $(storage_account)"
    echo "Key Vault: $(key_vault)"
    echo "MySQL Server: $(mysql_server)"
    echo "App1 Hostname: $(app1)"