trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.5.0'

steps:
# Install Terraform
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.5.0'

# Terraform Init
- task: TerraformCLI@1
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

# Terraform Plan
- task: TerraformCLI@1
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: 'ado-terraform-sp'
    commandOptions: '-var-file="terraform.tfvars"'

# Terraform Apply
- task: TerraformCLI@1
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: 'ado-terraform-sp'
    commandOptions: '-auto-approve -var-file="terraform.tfvars"'
